# Generated by Django 5.1.3 on 2024-11-20 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='banos',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='habitaciones',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='baños',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dormitorios',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('en_alquiler', 'En Alquiler')], default='en_alquiler', max_length=20),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_inmuebles/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen_autor',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_autores/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='nombre_autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='titulo_autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estacionamientos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.comuna'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.region'),
        ),
    ]
