# Generated by Django 5.1.3 on 2024-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_comuna_region_remove_inmueble_banos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
