# Generated by Django 5.1.3 on 2024-11-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_alter_inmueble_precio_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.region'),
        ),
    ]
